import { PageHeader } from '@/components/dashboard/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function PrivacyPolicyPage() {
  return (
      <div className="container mx-auto p-4 md:p-6 lg:p-8">
        <PageHeader
          title="Privacy Policy"
          description="Last updated: August 08, 2025"
        />
        <Card>
          <CardContent className="prose prose-sm sm:prose-base dark:prose-invert max-w-none pt-6 space-y-4">
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </p>

            <h2 className="font-bold text-xl">Interpretation and Definitions</h2>
            <h3 className="font-semibold">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have
              meanings defined under the following conditions. The following
              definitions shall have the same meaning regardless of whether
              they appear in singular or in plural.
            </p>
            <h3 className="font-semibold">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>We</strong> (referred to as either "the Developer", "We",
                "Us" or "Our" in this Agreement) refers to booskit.dev.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on
                Your computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website
                among its many uses.
              </li>
              <li>
                <strong>Country</strong> refers to: San Andreas
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Website.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>
              <li>
                <strong>Website</strong> refers to LEO Assistant+, accessible
                from your current URL.
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using
                the Service, or the developer, or other legal entity on behalf
                of which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>

            <h2 className="font-bold text-xl">Collecting and Using Your Personal Data</h2>
            <p>
                This service exclusively uses your browser's `localStorage` and `sessionStorage` to store data. We do not have a backend database that stores user-specific information. All data, including your officer details, alternative characters, and in-progress reports, remains on your device.
            </p>
            <ul className="list-disc pl-6 space-y-2">
                <li><strong>localStorage:</strong> Used for persisting your default officer settings and alternative characters across browser sessions.</li>
                <li><strong>sessionStorage:</strong> Used for temporarily storing data related to the current session, such as charges added to the calculator and partially filled reports. This data is cleared when you close your browser tab.</li>
            </ul>

             <h2 className="font-bold text-xl">Use of Your Personal Data</h2>
            <p>The Developer may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
                <li>
                    <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
                </li>
            </ul>
            
            <h2 className="font-bold text-xl">Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </p>

            <h2 className="font-bold text-xl">Children's Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 13. We do
              not knowingly collect personally identifiable information from
              anyone under the age of 13. If You are a parent or guardian and
              You are aware that Your child has provided Us with Personal
              Data, please contact Us. If We become aware that We have
              collected Personal Data from anyone under the age of 13 without
              verification of parental consent, We take steps to remove that
              information from Our servers.
            </p>

            <h2 className="font-bold text-xl">Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third party link, You will be
              directed to that third party's site. We strongly advise You to
              review the Privacy Policy of every site You visit.
            </p>
            <p>
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites
              or services.
            </p>

            <h2 className="font-bold text-xl">Changes to this Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will
              notify You of any changes by posting the new Privacy Policy on
              this page.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for
              any changes. Changes to this Privacy Policy are effective when
              they are posted on this page.
            </p>

            <h2 className="font-bold text-xl">Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, You can
              contact us via the site administrator.
            </p>
          </CardContent>
        </Card>
      </div>
  );
}
